---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

version: '0.2'

enableGlobDot: true

dictionaryDefinitions:
  - name: base-dict
    path: './.cspell/dicts/base.txt'
    addWords: true

  - name: project-dict
    path: './.cspell/dicts/project.txt'
    addWords: true

dictionaries:
  - base-dict
  - project-dict

ignorePaths:
  - '.git'
  - '.vscode'
  - 'node_modules'
