[package]
name = "zism"
version = "0.4.1"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["okkey"]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4", features = ["derive"] }
inquire = "0.9.4"
self_update = { version = "1.0", default-features = false, features = ["reqwest", "archive-tar", "archive-zip", "compression-flate2", "rustls"] }

[dev-dependencies]
serial_test = "4"
