name: Check Markdown

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".github/workflows/check-markdown.yml"
      - ".markdownlint-cli2.jsonc"
      - "mise.lock"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/check-markdown.yml"
      - ".markdownlint-cli2.jsonc"
      - "mise.lock"

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install mise and setup
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          install: true
          install_args: "markdownlint-cli2"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          MISE_LOCKED: "1"

      - name: Fix
        run: mise md-fix

      - name: Commit and Push
        uses: 23prime/simple-commit-and-push@15fb653b9591afde3bffb82a906a9af2aede1616 # v1.0.0
        with:
          commit-message: "Auto fix by workflow"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        run: mise md-check
