name: Check GitHub workflow

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*.yml"
      - "mise.lock"
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - "mise.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: cicd-sensor
        uses: cicd-sensor/cicd-sensor-action@2b76335ff1c2dd298e983961f7a200d3fe9076c2 # v0.0.36

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install mise and setup
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install: true
          install_args: "actionlint shellcheck zizmor"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          MISE_LOCKED: "1"

      - name: Check
        run: mise run gh-check
