name: Check Markdown

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".github/workflows/check-markdown.yml"
      - ".markdownlint-cli2.jsonc"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/check-markdown.yml"
      - ".markdownlint-cli2.jsonc"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install mise and setup
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install: true
          install_args: "markdownlint-cli2"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix
        run: mise md-fix

      - name: Commit and Push
        uses: 23prime/simple-commit-and-push@15fb653b9591afde3bffb82a906a9af2aede1616 # v1.0.0
        with:
          commit-message: "Auto fix by workflow"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        run: mise md-check
