name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Sync upstream
        uses: 23prime/sync-upstream@c6fd3628a9f3ed61eec932f3b27e854356c43a9f # v1.0.1
        with:
          upstream-url: https://github.com/23prime/mise-template.git
          github-token: ${{ secrets.GITHUB_TOKEN }}
