name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Sync upstream
        uses: 23prime/sync-upstream@6bdce9e135503a87b05c5836b0bc2b0d8db0786d # v1.0.0
        with:
          upstream-url: https://github.com/23prime/mise-template.git
          github-token: ${{ secrets.GITHUB_TOKEN }}
