name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write # push synced commits
      pull-requests: write # create the sync PR

    steps:
      - name: cicd-sensor
        uses: cicd-sensor/cicd-sensor-action@31366296cb918b7f1413829aafc16dcf18fe8518 # v0.0.35

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Sync upstream
        uses: 23prime/sync-upstream@01b700f2e968c11b4631d6f50a28dd0750deca10 # v1.1.1
        with:
          upstream-url: https://github.com/23prime/mise-template.git
          github-token: ${{ secrets.GITHUB_TOKEN }}
